export const experienceDataFrontend=[
    {
        id:1,
        image:"https://w7.pngwing.com/pngs/410/100/png-transparent-web-development-html-responsive-web-design-logo-javascript-html-angle-web-design-text-thumbnail.png",
        title:"HTMl",
        level:4
    },
    {
        id:2,
        image:"https://w7.pngwing.com/pngs/393/49/png-transparent-css-logo-thumbnail.png",
        title:"CSS",
        level:4
    },
    {
        id:3,
        image:"https://w7.pngwing.com/pngs/793/545/png-transparent-javascript-programmer-node-js-web-application-markup-language-thumbnail.png",
        title:"Javacript",
        level:4
    },
    {
        id:4,
        image:"https://w7.pngwing.com/pngs/79/518/png-transparent-js-react-js-logo-react-react-native-logos-icon-thumbnail.png",
        title:"React js",
        level:4
    },
    {
        id:4,
        image:"https://w7.pngwing.com/pngs/669/447/png-transparent-redux-react-javascript-freecodecamp-npm-others-miscellaneous-purple-violet-thumbnail.png",
        title:"Redux Toolkit",
        level:4
    },
    {
        id:1,
        image:"https://w7.pngwing.com/pngs/293/485/png-transparent-tailwind-css-hd-logo-thumbnail.png",
        title:"Tailwind CSS",
        level:4
    },
    {
        id:1,
        image:"https://w7.pngwing.com/pngs/104/793/png-transparent-bootstrap-hd-logo-thumbnail.png",
        title:"Bootstap",
        level:4
    },
]
export const experienceDataBackend=[
    {
        id:1,
        image:"https://w7.pngwing.com/pngs/452/24/png-transparent-js-logo-node-logos-and-brands-icon-thumbnail.png",
        title:"Node js",
        level:4
    },
    {
        id:2,
        image:"https://w7.pngwing.com/pngs/768/167/png-transparent-mongodb-nosql-document-oriented-database-nosql-icon-leaf-grass-business-thumbnail.png",
        title:"MongoDB",
        level:4
    },
    {
        id:3,
        image:"https://w1.pngwing.com/pngs/711/379/png-transparent-green-grass-mongodb-database-documentoriented-database-dashboard-nosql-bson-javascript-thumbnail.png",
        title:"Mongoose",
        level:4
    },
    {
        id:4,
        image:"https://w7.pngwing.com/pngs/925/447/png-transparent-express-js-node-js-javascript-mongodb-node-js-text-trademark-logo-thumbnail.png",
        title:"Express js",
        level:4
    },
    {
        id:4,
        image:"https://w7.pngwing.com/pngs/385/582/png-transparent-mysql-workbench-macos-bigsur-icon-thumbnail.png",
        title:"MySQL",
        level:4
    },
    {
        id:1,
        image:"https://w7.pngwing.com/pngs/255/665/png-transparent-oval-blue-and-black-php-logo-php-server-side-scripting-computer-software-general-purpose-programming-language-php-miscellaneous-blue-text-thumbnail.png",
        title:"PHP",
        level:4
    },
    {
        id:1,
        image:"https://w7.pngwing.com/pngs/578/816/png-transparent-java-class-file-java-platform-standard-edition-java-development-kit-java-runtime-environment-coffee-jar-text-class-orange-thumbnail.png",
        title:"Java",
        level:4
    },
]
export const experienceOtherData=[
    {
        id:1,
        image:"https://w7.pngwing.com/pngs/724/306/png-transparent-c-logo-c-programming-language-icon-letter-c-blue-logo-computer-program-thumbnail.png",
        title:"C language",
    },
    {
        id:2,
        image:"https://w7.pngwing.com/pngs/46/626/png-transparent-c-logo-the-c-programming-language-computer-icons-computer-programming-source-code-programming-miscellaneous-template-blue-thumbnail.png",
        title:"C++ language",
    },
    {
        id:3,
        image:"https://w1.pngwing.com/pngs/711/379/png-transparent-green-grass-mongodb-database-documentoriented-database-dashboard-nosql-bson-javascript-thumbnail.png",
        title:"Mongoose",
    },
    {
        id:4,
        image:"https://w7.pngwing.com/pngs/925/447/png-transparent-express-js-node-js-javascript-mongodb-node-js-text-trademark-logo-thumbnail.png",
        title:"Express js",
    },
    {
        id:4,
        image:"https://w7.pngwing.com/pngs/385/582/png-transparent-mysql-workbench-macos-bigsur-icon-thumbnail.png",
        title:"MySQL",
    },
    {
        id:1,
        image:"https://w7.pngwing.com/pngs/255/665/png-transparent-oval-blue-and-black-php-logo-php-server-side-scripting-computer-software-general-purpose-programming-language-php-miscellaneous-blue-text-thumbnail.png",
        title:"PHP",
    },
    {
        id:1,
        image:"https://w7.pngwing.com/pngs/578/816/png-transparent-java-class-file-java-platform-standard-edition-java-development-kit-java-runtime-environment-coffee-jar-text-class-orange-thumbnail.png",
        title:"Java",
    },
]